import shutil
import subprocess
import hashlib
from pathlib import Path

import pytest

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
SOURCE = HERE / "test_app_launcher_nomadnet.cpp"
INCLUDE = ROOT / "lib" / "tdeck_ui" / "UI" / "LXMF"
FIXTURES = {
    HERE / "fixtures" / "nomadnet_readme.mu":
        "e47de4e19e7216e48a8d441abbca1650b77ab6a2b47bedbd2144301f44172728",
    HERE / "fixtures" / "columba_releases_live.mu":
        "1ea4eea2b06d6988c53c19df51d38f78abd27125b4613f7a3fa5715f7461b10a",
}


def _cxx():
    for name in ("clang++", "g++"):
        if shutil.which(name):
            return name
    pytest.skip("no C++ compiler found")


def test_app_launcher_nomadnet_native(tmp_path):
    # Exact upstream NomadNet 1.2.8 README.mu plus Micron generated by
    # the live Columba Releases service; hashes prevent fixture drift. The
    # Columba fixture is LF-normalized from raw artifact SHA-256:
    # 6b93c458d31e3b74c33a0cd0333582a69a3ffd0b0033c2a228b0a85da779e37f.
    for fixture, expected_hash in FIXTURES.items():
        assert hashlib.sha256(fixture.read_bytes()).hexdigest() == expected_hash
    binary = tmp_path / "test_app_launcher_nomadnet"
    command = [
        _cxx(), "-std=c++17", "-Wall", "-Wextra", "-Werror",
        f"-I{INCLUDE}", str(SOURCE),
        str(INCLUDE / "NomadNetDocument.cpp"),
        str(INCLUDE / "NomadNetUrl.cpp"),
        "-o", str(binary),
    ]
    compiled = subprocess.run(command, capture_output=True, text=True)
    assert compiled.returncode == 0, compiled.stdout + compiled.stderr
    for fixture in FIXTURES:
        result = subprocess.run([str(binary), str(fixture)], capture_output=True, text=True, timeout=30)
        assert result.returncode == 0, result.stdout + result.stderr
        assert result.stdout.strip().endswith("passed, 0 failed")


def test_ui_wiring_contract():
    manager_h = (INCLUDE / "UIManager.h").read_text()
    manager_cpp = (INCLUDE / "UIManager.cpp").read_text()
    launcher_cpp = (INCLUDE / "HomeScreen.cpp").read_text()
    network_cpp = (INCLUDE / "NetworkScreen.cpp").read_text()
    browser_cpp = (INCLUDE / "NomadNetScreen.cpp").read_text()

    for tile in ("Messages", "NomadNet", "Network", "Settings"):
        assert tile in launcher_cpp
    for child in ("Announces", "Status", "Radio Activity", "Propagation Nodes"):
        assert child in network_cpp
    assert "NavigationStack" in manager_h
    assert "void UIManager::navigate(" in manager_cpp
    assert "void UIManager::back()" in manager_cpp
    assert "void UIManager::home()" in manager_cpp
    assert "SCREEN_" not in manager_h
    assert "nomadnetwork\", \"node" in manager_cpp
    assert "Identity::recall" in manager_cpp
    assert "Transport::request_path" in manager_cpp
    assert "no_form_request_data" in manager_cpp
    assert "response_transfer_size()" in manager_cpp
    assert "DEPENDENCY HARDENING GAP" in manager_cpp
    assert "lv_obj_set_scroll_dir" in browser_cpp
    assert "lv_textarea_set_max_length" in browser_cpp
    assert "set_link_callback" in manager_cpp
    assert "_link_targets" in browser_cpp
    assert "LV_SYMBOL_HOME" in browser_cpp
    assert "lv_font_" in browser_cpp
    for detail in ("Inbox & calls", "Browse Micron", "Links & radio", "Device options"):
        assert detail in launcher_cpp
    for detail in ("Discovered peers", "Interfaces & storage", "Signal history", "Delivery relays"):
        assert detail in network_cpp
    assert "set_address_editing(false)" in browser_cpp
    assert "_address_summary" in browser_cpp
    assert "for(auto* button:{_back_button,_home_button})" in network_cpp
