import shutil
import subprocess
import hashlib
import re
from pathlib import Path

import pytest

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
SOURCE = HERE / "test_app_launcher_nomadnet.cpp"
INCLUDE = ROOT / "lib" / "tdeck_ui" / "UI" / "LXMF"
FIXTURES = {
    HERE / "fixtures" / "nomadnet_readme.mu":
        "e47de4e19e7216e48a8d441abbca1650b77ab6a2b47bedbd2144301f44172728",
    HERE / "fixtures" / "columba_releases_live.mu":
        "1ea4eea2b06d6988c53c19df51d38f78abd27125b4613f7a3fa5715f7461b10a",
}


def _cxx():
    for name in ("clang++", "g++"):
        if shutil.which(name):
            return name
    pytest.skip("no C++ compiler found")


def test_app_launcher_nomadnet_native(tmp_path):
    # Exact upstream NomadNet 1.2.8 README.mu plus Micron generated by
    # the live Columba Releases service; hashes prevent fixture drift. The
    # Columba fixture is LF-normalized from raw artifact SHA-256:
    # 6b93c458d31e3b74c33a0cd0333582a69a3ffd0b0033c2a228b0a85da779e37f.
    for fixture, expected_hash in FIXTURES.items():
        assert hashlib.sha256(fixture.read_bytes()).hexdigest() == expected_hash
    binary = tmp_path / "test_app_launcher_nomadnet"
    command = [
        _cxx(), "-std=c++17", "-Wall", "-Wextra", "-Werror",
        f"-I{INCLUDE}", str(SOURCE),
        str(INCLUDE / "NomadNetDocument.cpp"),
        str(INCLUDE / "NomadNetCompactPage.cpp"),
        str(INCLUDE / "NomadNetForm.cpp"),
        str(INCLUDE / "NomadNetGlyphs.cpp"),
        str(INCLUDE / "NomadNetLibrary.cpp"),
        str(INCLUDE / "NomadNetUrl.cpp"),
        "-o", str(binary),
    ]
    compiled = subprocess.run(command, capture_output=True, text=True)
    assert compiled.returncode == 0, compiled.stdout + compiled.stderr
    for fixture in FIXTURES:
        result = subprocess.run([str(binary), str(fixture)], capture_output=True, text=True, timeout=30)
        assert result.returncode == 0, result.stdout + result.stderr
        assert result.stdout.strip().endswith("passed, 0 failed")


def test_form_empty_selector_allocation_failure_is_contained(tmp_path):
    binary = tmp_path / "test_nomadnet_form_alloc_failure"
    source = HERE / "test_nomadnet_form_alloc_failure.cpp"
    command = [
        _cxx(), "-std=c++17", "-Wall", "-Wextra", "-Werror",
        f"-I{INCLUDE}", str(source),
        str(INCLUDE / "NomadNetDocument.cpp"),
        str(INCLUDE / "NomadNetCompactPage.cpp"),
        str(INCLUDE / "NomadNetForm.cpp"),
        str(INCLUDE / "NomadNetGlyphs.cpp"),
        "-o", str(binary),
    ]
    compiled = subprocess.run(command, capture_output=True, text=True)
    assert compiled.returncode == 0, compiled.stdout + compiled.stderr
    result = subprocess.run([str(binary)], capture_output=True, text=True, timeout=30)
    assert result.returncode == 0, result.stdout + result.stderr


def test_ui_wiring_contract():
    library_json = (ROOT / "lib" / "tdeck_ui" / "library.json").read_text()
    manager_h = (INCLUDE / "UIManager.h").read_text()
    manager_cpp = (INCLUDE / "UIManager.cpp").read_text()
    launcher_cpp = (INCLUDE / "HomeScreen.cpp").read_text()
    network_cpp = (INCLUDE / "NetworkScreen.cpp").read_text()
    browser_cpp = (INCLUDE / "NomadNetScreen.cpp").read_text()
    glyphs_h = (INCLUDE / "NomadNetGlyphs.h").read_text()

    for tile in ("Messages", "NomadNet", "Network", "Settings", "Maps"):
        assert tile in launcher_cpp
    for child in ("Status", "Radio Activity", "Propagation Nodes"):
        assert child in network_cpp
    assert "Announces" not in network_cpp
    assert "set_peers_callback" in manager_cpp
    assert "_nomad_actions.publish" in manager_cpp
    assert "nomad_update_user_actions();" in manager_cpp
    assert "begin_navigation" in browser_cpp
    assert "clear_document" in browser_cpp
    assert "NavigationStack" in manager_h
    assert "void UIManager::navigate(" in manager_cpp
    assert "void UIManager::back()" in manager_cpp
    assert "void UIManager::home()" in manager_cpp
    assert "SCREEN_" not in manager_h
    assert "nomadnetwork\", \"node" in manager_cpp
    assert "Identity::recall" in manager_cpp
    assert "Transport::request_path" in manager_cpp
    assert "request_data(_nomad_url.fields)" in manager_cpp
    request_start = manager_cpp.index("void UIManager::nomad_send_request()")
    request = manager_cpp[request_start:manager_cpp.index("void UIManager::nomad_update()", request_start)]
    assert "30.0, NomadNet::AsyncMailbox::MAX_WIRE_BYTES" in request
    failed = manager_cpp[manager_cpp.index("void UIManager::on_nomad_failed"):
                         manager_cpp.index("void UIManager::on_nomad_progress")]
    assert "receipt.response_size()" in failed
    assert "publish_oversized" in failed
    assert "response_transfer_size()" in manager_cpp
    assert "DEPENDENCY HARDENING GAP" not in manager_cpp
    assert "lv_obj_set_scroll_dir" in browser_cpp
    assert "lv_textarea_set_max_length" in browser_cpp
    assert "set_link_callback" in manager_cpp
    assert "_page.target(" in browser_cpp
    assert "lv_obj_scroll_to_y(_content,0,LV_ANIM_OFF);" in browser_cpp
    assert "lv_group_focus_obj(_focusables.front())" not in browser_cpp
    assert "LV_SYMBOL_HOME" in browser_cpp
    assert "lv_font_" in browser_cpp
    assert "nomadnet_font_12" in browser_cpp
    assert "nomadnet_font_16" in browser_cpp
    assert "display_text" in browser_cpp
    assert "U+00A0-U+017F" in glyphs_h
    assert "U+2000-U+206F" in glyphs_h
    assert "U+2190-U+21FF" in glyphs_h
    assert "+<UI/Fonts/*.c>" in library_json
    for detail in ("Inbox & calls", "Browse Micron", "Links & radio", "Device options",
                   "Offline SD packs"):
        assert detail in launcher_cpp
    for detail in ("Interfaces & storage", "Signal history", "Delivery relays"):
        assert detail in network_cpp
    assert "show_browser(false)" in browser_cpp
    assert "_address_summary" in browser_cpp
    assert "for(auto* button:{_back_button,_home_button})" in network_cpp
    for section in ("Heard Nodes", "Saved Nodes", "Saved Pages", "Recent Pages", "Enter Address"):
        assert section in browser_cpp
    assert "handle_library_back" in browser_cpp
    assert "set_library" in browser_cpp
    assert "set_save_callback" in manager_cpp


def test_nomadnet_forms_are_bounded_virtualized_and_owner_submitted():
    document_h = (INCLUDE / "NomadNetDocument.h").read_text()
    form_h = (INCLUDE / "NomadNetForm.h").read_text()
    form_cpp = (INCLUDE / "NomadNetForm.cpp").read_text()
    compact_h = (INCLUDE / "NomadNetCompactPage.h").read_text()
    screen = (INCLUDE / "NomadNetScreen.cpp").read_text()
    manager = (INCLUDE / "UIManager.cpp").read_text()
    x86_client = (ROOT / "tests/native/nomadnet_x86_flow/client.cpp").read_text()
    platformio = (ROOT / "platformio.ini").read_text()
    lvgl_patch = (ROOT / "patch_lvgl_textarea.py").read_text()

    assert "pre:patch_lvgl_textarea.py" in platformio
    assert "if(obj == NULL) return NULL;" in lvgl_patch
    assert "if(ta->label == NULL)" in lvgl_patch
    assert "char * pwd_resized" in lvgl_patch
    assert "ta->pwd_tmp = pwd_resized" in lvgl_patch
    assert "ta->pwd_tmp = pwd_bulk_resized" in lvgl_patch
    assert "if(pwd_shrunk != NULL) ta->pwd_tmp = pwd_shrunk" in lvgl_patch
    assert "ta->pwd_tmp = pwd_set_resized" in lvgl_patch
    assert "lv_obj_class_create_obj(&lv_label_class, obj)" in lvgl_patch
    assert "char * pwd_mode_tmp = lv_mem_alloc(len + 1)" in lvgl_patch
    assert "ta->pwd_mode = 1U" in lvgl_patch
    assert "if(pwd_resized == NULL) return;\\n        ta->pwd_tmp = pwd_resized;" in lvgl_patch
    assert "if(pwd_bulk_resized == NULL) return;\\n        ta->pwd_tmp = pwd_bulk_resized;" in lvgl_patch
    assert "Reserve password storage before mutating the label" in lvgl_patch
    assert 'env_libdeps_dir(env, "lvgl", "src", "core", "lv_obj_class.c")' in lvgl_patch
    assert 'env_libdeps_dir(env, "lvgl", "src", "widgets", "lv_label.c")' in lvgl_patch
    assert "if(parent->spec_attr == NULL)" in lvgl_patch
    assert "lv_obj_t ** children_resized" in lvgl_patch
    assert "char * label_resized = lv_mem_realloc" in lvgl_patch
    assert "if(txt_tmp == NULL) {" in lvgl_patch
    assert "volatile char * visible" in lvgl_patch
    assert "size_t visible_len = strlen(txt)" in lvgl_patch
    assert "size_t masked_len = strlen(visible)" in lvgl_patch
    assert 'env_libdeps_dir(env, "lvgl", "src", "core", "lv_event.c")' in lvgl_patch
    assert 'env_libdeps_dir(env, "lvgl", "src", "core", "lv_group.c")' in lvgl_patch
    assert "lv_event_dsc_t * event_dsc_resized" in lvgl_patch
    assert "uint32_t event_dsc_cnt_new" in lvgl_patch
    assert "if(lv_label_get_text(ta->label) == NULL)" in lvgl_patch
    assert "lv_obj_add_event_cb(ta->label, label_event_cb" in lvgl_patch
    assert "obj->spec_attr->group_p = group;" in lvgl_patch
    group_patch = lvgl_patch[lvgl_patch.index("group_add_new ="):]
    assert group_patch.index("lv_obj_t ** next = _lv_ll_ins_tail") < group_patch.index(
        "obj->spec_attr->group_p = group;"
    )

    for bound in ("MAX_FIELDS", "MAX_FIELD_NAME_BYTES", "MAX_FIELD_VALUE_BYTES",
                  "MAX_FIELD_LABEL_BYTES", "MAX_FORM_BYTES", "MAX_ENCODED_BYTES"):
        assert bound in document_h or bound in form_h
    assert "ExternalVector<FieldRecord>" in compact_h
    assert "ExternalVector<FieldState>" in form_h
    assert "field_index" in compact_h
    assert "clear_encoded_form" in form_cpp
    assert "~FieldState" in form_h
    constructor = screen[screen.index("NomadNetScreen::NomadNetScreen"):
                         screen.index("NomadNetScreen::~NomadNetScreen")]
    begin_edit = screen[screen.index("void NomadNetScreen::begin_field_edit"):
                        screen.index("void NomadNetScreen::finish_field_edit")]
    finish_edit = screen[screen.index("void NomadNetScreen::finish_field_edit"):
                         screen.index("void NomadNetScreen::activate_selected_link")]
    assert "_field_editor=lv_textarea_create" not in constructor
    assert begin_edit.count("_field_editor=lv_textarea_create") == 1
    assert "if(!_field_editor)" in begin_edit
    assert "Field editor is unavailable" in begin_edit
    assert "std::strcmp(loaded_value,state.value.data())!=0" in begin_edit
    assert "lv_textarea_get_text(_field_editor)==nullptr" in begin_edit
    assert "if(type==NomadNet::FormFieldType::PASSWORD&&\n       !lv_textarea_get_password_mode(_field_editor))" in begin_edit
    assert begin_edit.index("lv_textarea_set_password_mode(_field_editor,true)") < begin_edit.index(
        "!lv_textarea_get_password_mode(_field_editor)"
    ) < begin_edit.index("lv_textarea_set_text(_field_editor,state.value.data())")
    assert "const std::size_t wipe_length=std::strlen(value)" in begin_edit
    assert "if(!TextAreaHelper::enable_paste(_field_editor)" in begin_edit
    assert "!lv_obj_add_event_cb(_field_editor" in begin_edit
    assert "lv_obj_get_group(_field_editor)!=group" in begin_edit
    assert begin_edit.index("lv_group_add_obj(group,_field_editor)") < begin_edit.index(
        "lv_group_remove_obj(_content)"
    )
    assert "lv_obj_del(_field_editor)" in finish_edit
    assert "_field_editor=nullptr" in finish_edit
    form_layout = screen[screen.index("bool NomadNetScreen::layout_page()"):
                         screen.index("void NomadNetScreen::draw_page")]
    assert "lv_obj_create" not in form_layout
    assert "set_submit_callback" in manager
    assert "prepare_submission" in manager
    assert "_nomad_submission_ready" in manager
    request_start = manager.index("void UIManager::nomad_send_request()")
    request = manager[request_start:manager.index("void UIManager::nomad_update()", request_start)]
    assert "packed_request_data" in request
    assert "clear_encoded_form(_nomad_submission_data)" in request
    assert "catch (const std::bad_alloc&)" in request
    assert "Request exceeds available internal memory" in request
    assert "request_data.size() > NomadNet::FormState::MAX_ENCODED_BYTES" in request
    assert "Request data exceeds device limit" in request
    assert "NomadNet::AsyncMailbox::MAX_WIRE_BYTES, true" in request
    identify_link = manager[manager.index("void UIManager::nomad_identify_link_if_configured()"):
                            manager.index("void UIManager::nomad_send_request()")]
    assert "if (_nomad_library.node_identified(_nomad_url.destination_hex))" in identify_link
    assert "if (_nomad_link_identified) return;" in identify_link
    assert "_nomad_link.identify(_router.identity())" in identify_link
    link_event = manager[manager.index("case NomadNet::AsyncMailbox::Kind::LINK_ESTABLISHED"):
                         manager.index("case NomadNet::AsyncMailbox::Kind::LINK_CLOSED")]
    assert "nomad_identify_link_if_configured()" not in link_event
    assert request.count("nomad_identify_link_if_configured()") == 1
    assert request.index("nomad_identify_link_if_configured()") < request.index("_nomad_link.request(")
    assert "set_value(uint16_t id, const char* value, std::size_t size)" in form_h
    assert "MAX_ENCODED_BYTES = 384" in form_h
    prepare_submission = screen[screen.index("bool NomadNetScreen::prepare_submission"):
                                screen.index("void NomadNetScreen::field_editor_event")]
    assert "catch(const std::bad_alloc&)" in prepare_submission
    assert "FormEncodeResult::ALLOCATION_FAILED" in prepare_submission
    assert "set_identify_callback" in manager
    assert "set_identify_enabled" in manager
    assert "Deliberately no link.identify()" in x86_client


def test_nomadnet_table_renderer_is_bounded_and_virtualized():
    document_h = (INCLUDE / "NomadNetDocument.h").read_text()
    compact_h = (INCLUDE / "NomadNetCompactPage.h").read_text()
    screen_h = (INCLUDE / "NomadNetScreen.h").read_text()
    screen = (INCLUDE / "NomadNetScreen.cpp").read_text()
    manager = (INCLUDE / "UIManager.cpp").read_text()

    for bound in ("MAX_TABLES", "MAX_TABLE_ROWS", "MAX_TABLE_COLUMNS",
                  "MAX_TABLE_CELLS", "MAX_TOTAL_TABLE_CELLS", "MAX_TABLE_CELL_BYTES",
                  "MAX_TABLE_FALLBACK_BYTES", "MAX_TABLE_BYTES"):
        assert bound in document_h
    assert "const ExternalVector<TableRecord>& tables()" in compact_h
    assert "const ExternalVector<TableCellRecord>& table_cells()" in compact_h
    assert "bool layout_table(" in screen_h
    assert "table_fit_width" in screen
    assert "layout_table_reflow" in screen
    assert "fragment.table_cell" in screen
    assert "bool line_started=false" in screen
    assert "if(line_started||line_y==top)" in screen
    layout = screen[screen.index("bool NomadNetScreen::layout_table("):
                    screen.index("bool NomadNetScreen::layout_from(")]
    assert "lv_obj_create" not in layout
    assert "lv_label_create" not in layout
    parse_call = manager.index("_nomad_parser.parse(")
    parse_guard = manager[parse_call - 300:parse_call + 500]
    assert "try {" in parse_guard
    assert "catch (const std::bad_alloc&)" in parse_guard
    assert "Page is too large for available memory" in parse_guard
    # Allocation failure must relinquish the full normalized PSRAM buffer.
    assert "_nomad_response.release()" in manager


def test_nomadnet_anchor_navigation_stays_local_and_uses_layout_checkpoints():
    document_h = (INCLUDE / "NomadNetDocument.h").read_text()
    document = (INCLUDE / "NomadNetDocument.cpp").read_text()
    compact_h = (INCLUDE / "NomadNetCompactPage.h").read_text()
    screen_h = (INCLUDE / "NomadNetScreen.h").read_text()
    screen = (INCLUDE / "NomadNetScreen.cpp").read_text()
    manager_h = (INCLUDE / "UIManager.h").read_text()
    manager = (INCLUDE / "UIManager.cpp").read_text()

    assert "MAX_ANCHORS = 128" in document_h
    assert "MAX_ANCHOR_NAME_BYTES = 64" in document_h
    assert "add_anchor(doc, line.substr(name_start" in document
    assert "add_anchor(doc, heading_slug(heading)" in document
    assert "const ExternalVector<AnchorRecord>& anchors()" in compact_h
    assert "bool find_anchor(" in compact_h

    assert "bool jump_to_anchor(const std::string& name);" in screen_h
    assert "int32_t logical_scroll() const" in screen_h
    jump = screen[screen.index("bool NomadNetScreen::jump_to_anchor("):
                  screen.index("void NomadNetScreen::draw_page")]
    assert "_page.find_anchor(name,block_index)" in jump
    assert "_layout_checkpoints" in jump
    assert "scroll_to_logical(target,LV_ANIM_OFF)" in jump

    open_page = manager[manager.index("void UIManager::nomad_open("):
                        manager.index("void UIManager::nomad_reload()")]
    assert "_nomad_url.path,_nomad_url.fields" in open_page
    assert "NomadNet::should_jump_locally" in open_page
    local = open_page[open_page.index("NomadNet::should_jump_locally"):
                      open_page.index("_nomad_pending_scroll=restore_logical_scroll")]
    assert "_nomadnet_screen->jump_to_anchor(parsed.fragment)" in local
    assert "if(!resolved&&parsed.fragment.empty())return;" in local
    assert "_nomad_history.current_request_data()" in local
    assert "_nomad_history.open(parsed.str(), add_history, current_scroll," in local
    assert "nomad_send_request" not in local
    assert "begin_navigation" not in local

    request = manager[manager.index("void UIManager::nomad_send_request()"):
                      manager.index("bool UIManager::nomad_apply_page_bytes")]
    assert "_nomad_url.path.data()" in request
    assert "fragment" not in request

    response = manager[manager.index("case NomadNet::AsyncMailbox::Kind::RESPONSE:"):
                       manager.index("case NomadNet::AsyncMailbox::Kind::NONE:")]
    apply = manager[manager.index("bool UIManager::nomad_apply_page_document("):
                    manager.index("void UIManager::nomad_update()")]
    assert "nomad_apply_page_document(document, false)" in response
    assert "_nomadnet_screen->set_page(document)" in apply
    assert "_nomadnet_screen->jump_to_anchor(_nomad_url.fragment)" in apply
    assert "_nomadnet_screen->restore_logical_scroll(_nomad_pending_scroll)" in apply
    assert "if (applied && _nomad_pending_scroll >= 0)" in apply
    assert "else if (applied && _nomad_url.has_fragment)" in apply
    assert (apply.index("_nomadnet_screen->restore_logical_scroll(_nomad_pending_scroll)") <
            apply.index("_nomadnet_screen->jump_to_anchor(_nomad_url.fragment)"))
    assert "Unknown anchor: #" in apply
    assert "int32_t _nomad_pending_scroll" in manager_h


def test_nomadnet_page_body_uses_one_compact_custom_viewport():
    screen_h = (INCLUDE / "NomadNetScreen.h").read_text()
    screen = (INCLUDE / "NomadNetScreen.cpp").read_text()
    compact_h = (INCLUDE / "NomadNetCompactPage.h").read_text()

    set_page = screen[screen.index("bool NomadNetScreen::set_page("):
                      screen.index("void NomadNetScreen::show()")]
    assert "_page.assign(document)" in set_page
    assert "lv_obj_clean(_content)" not in set_page
    assert "lv_spangroup_create" not in set_page
    assert "lv_spangroup_new_span" not in set_page
    assert "lv_btn_create(_content)" not in set_page
    assert "lv_label_create(_content)" not in set_page
    assert "LV_EVENT_DRAW_MAIN" in screen
    assert "lv_draw_label(" in screen
    assert "divider_height=static_cast<int16_t>(nomadnet_font_12.line_height)" in screen
    assert "divider_height=16" not in screen
    assert "commit_line" in screen
    assert "NomadNet::truncation_notice(document)" in set_page
    assert "if(!_page.append_notice(notice))" in set_page
    assert "if(!layout_page())" in set_page
    assert "catch(const std::bad_alloc&)" in set_page
    assert "Page is too large for available memory" in set_page
    assert "[Page truncated to device safety limits]" not in set_page
    assert "[Unsupported Micron content]" in screen
    assert "lv_obj_set_scroll_dir(_content,LV_DIR_VER)" in screen
    assert "CompactPage _page;" in screen_h
    assert "std::vector<std::string> _link_targets" not in screen_h
    assert "ExternalVector<char> _arena" in compact_h
    assert "uint32_t text_offset" in compact_h
    assert "uint32_t target_offset" in compact_h
    assert "MAX_ARENA_BYTES" in compact_h
    compact_cpp = (INCLUDE / "NomadNetCompactPage.cpp").read_text()
    assert "const std::string rendered_text" not in compact_cpp
    assert "visit_display_text" in compact_cpp
    assert "lv_indev_get_type(indev)!=LV_INDEV_TYPE_POINTER" in screen
    assert "MAX_WINDOW_FRAGMENTS" in screen_h
    assert "MAX_LAYOUT_FRAGMENTS" not in screen_h
    assert "ExternalVector<LayoutCheckpoint> _layout_checkpoints" in screen_h
    assert "_layout_window_top" in screen_h
    assert "_logical_scroll" in screen_h
    assert "ExternalVector<int32_t> _link_bottom" in screen_h
    assert "_link_bottom[run.link_index]=std::max" in screen
    assert "link_top+19" not in screen
    assert "layout_window(" in screen
    assert "VirtualViewport::logical_from_physical" in screen
    assert "VirtualViewport::physical_from_logical" in screen
    assert "lv_obj_get_content_coords(_content,&content_area)" in screen
    assert "draw_ctx->clip_area=&content_clip" in screen
    assert "_lv_area_is_point_on(&content_area,&point,0)" in screen
    assert "[Page layout truncated:" not in screen
    assert "content_fragment_limit" not in screen
    assert "whitespace&&x+fragment_w>indent+available" in screen
    assert "for(int attempt=0;attempt<count;++attempt)" in screen
    assert "_link_y[candidate]>=0" in screen
    assert "lv_group_set_editing(group,false)" in screen


def test_successful_page_application_releases_normalized_response():
    manager = (INCLUDE / "UIManager.cpp").read_text()
    response = manager[manager.index("case NomadNet::AsyncMailbox::Kind::RESPONSE:"):
                       manager.index("case NomadNet::AsyncMailbox::Kind::NONE:")]
    checkpoint = response.index('nomad_heap_checkpoint("response-page-applied")')
    assert response.index("_nomad_response.take()", checkpoint) > checkpoint
    assert response.index("_nomad_response.release()", checkpoint) > checkpoint


def test_cache_lookup_preserves_page_and_response_uses_captured_request_class():
    manager = (INCLUDE / "UIManager.cpp").read_text()
    header = (INCLUDE / "UIManager.h").read_text()
    open_page = manager[manager.index("void UIManager::nomad_open("):
                        manager.index("void UIManager::nomad_reload()")]
    lookup = open_page.index("_nomad_cache_flow.begin")
    assert "begin_navigation" not in open_page[:lookup]
    assert "_nomad_request_data_class" in header
    assert open_page.index("_nomad_request_data_class = _nomad_submission_ready") < lookup
    send = manager[manager.index("void UIManager::nomad_send_request()"):
                   manager.index("bool UIManager::nomad_apply_page_bytes")]
    assert "_nomad_request_data_class =" not in send
    assert "_nomad_submission_ready = false" in send
    response = manager[manager.index("case NomadNet::AsyncMailbox::Kind::RESPONSE:"):
                       manager.index("case NomadNet::AsyncMailbox::Kind::NONE:")]
    assert "_nomad_request_data_class == NomadNet::RequestDataClass::NIL" in response
    assert "!_nomad_submission_ready" not in response


def test_directory_rebuild_has_one_final_focus_owner():
    """Returning from Heard Nodes must not focus every surviving/start row."""
    screen = (INCLUDE / "NomadNetScreen.cpp").read_text()
    render_start = screen.index("void NomadNetScreen::render_directory(View view)")
    detach_start = screen.index("void NomadNetScreen::detach_focusables(", render_start)
    rebuild_start = screen.index("void NomadNetScreen::rebuild_focus()", detach_start)
    clear_start = screen.index("void NomadNetScreen::clear_directory()")
    clear = screen[clear_start:screen.index("void NomadNetScreen::begin_navigation(", clear_start)]
    render = screen[render_start:detach_start]
    detach = screen[detach_start:rebuild_start]
    rebuild_end = screen.index("void NomadNetScreen::apply_browser_layout", rebuild_start)
    rebuild = screen[rebuild_start:rebuild_end]

    # Creating replacement buttons must not auto-enrol/focus the first object
    # through LVGL's default-group constructor hook.
    assert "clear_directory();" in render
    assert "detach_focusables(group);" in clear
    assert "lv_group_set_default(nullptr);" in render
    assert "lv_group_set_default(previous_default_group);" in render
    assert render.index("clear_directory();") < render.index("lv_group_set_default(nullptr);")
    assert render.index("lv_group_set_default(nullptr);") < render.index("auto add_row=")
    assert render.index("lv_group_set_default(previous_default_group);") > render.index("if(_directory_focusables.empty())")

    # Detach every non-owner first and the current owner last. LVGL 8.4
    # otherwise refocuses each remaining member synchronously during removal.
    assert "auto* focused=lv_group_get_focused(group);" in detach
    assert "if(object&&object!=focused)lv_group_remove_obj(object);" in detach
    assert "if(focused&&owned_focusable(focused))lv_group_remove_obj(focused);" in detach
    assert detach.index("if(object&&object!=focused)lv_group_remove_obj(object);") < detach.index(
        "if(focused&&owned_focusable(focused))lv_group_remove_obj(focused);"
    )

    # Repopulate while frozen, then emit exactly one intentional final focus.
    assert "detach_focusables(group);" in rebuild
    assert "lv_group_focus_freeze(group,true);" in rebuild
    assert "lv_group_focus_freeze(group,false);" in rebuild
    assert rebuild.index("lv_group_focus_freeze(group,true);") < rebuild.index("lv_group_add_obj")
    assert rebuild.index("lv_group_focus_freeze(group,false);") < rebuild.rindex("lv_group_focus_obj")


def test_begin_navigation_releases_directory_rows_before_transport():
    """Hidden directory rows must not consume Wi-Fi/Link internal SRAM."""
    screen_h = (INCLUDE / "NomadNetScreen.h").read_text()
    screen = (INCLUDE / "NomadNetScreen.cpp").read_text()

    clear_start = screen.index("void NomadNetScreen::clear_directory()")
    begin_start = screen.index("void NomadNetScreen::begin_navigation(")
    show_start = screen.index("void NomadNetScreen::show_start()", begin_start)
    clear = screen[clear_start:begin_start]
    begin = screen[begin_start:show_start]

    assert "void clear_directory();" in screen_h
    assert "detach_focusables(group);" in clear
    assert "lv_obj_clean(_directory);" in clear
    assert "std::vector<lv_obj_t*>().swap(_directory_focusables);" in clear
    assert "std::vector<std::string>().swap(_directory_targets);" in clear
    assert "clear_directory();" in begin
    assert begin.index("clear_directory();") < begin.index("show_browser(false);")


def test_nomadnet_validates_queued_addresses_before_navigation_teardown():
    """A malformed manual address must preserve the current page or directory."""
    screen = (INCLUDE / "NomadNetScreen.cpp").read_text()
    manager = (INCLUDE / "UIManager.cpp").read_text()

    # UI callbacks enqueue only; the owner validates before starting navigation.
    activate = screen[screen.index("void NomadNetScreen::activate_selected_link()"):
                      screen.index("void NomadNetScreen::page_event")]
    clicked = screen[screen.index("void NomadNetScreen::clicked("):]
    assert "begin_navigation(" not in activate
    assert "begin_navigation(" not in clicked

    actions = manager[manager.index("void UIManager::nomad_update_user_actions()"):
                      manager.index("void UIManager::service_nomad_terminal_action()")]
    assert "begin_navigation(" not in actions

    open_page = manager[manager.index("void UIManager::nomad_open("):
                        manager.index("void UIManager::nomad_reload()")]
    parse = open_page.index("NomadNet::Url::parse")
    lookup = open_page.index("_nomad_cache_flow.begin")
    assert parse < lookup
    assert "begin_navigation" not in open_page[:lookup]
    live = manager[manager.index("void UIManager::nomad_begin_live_transport()"):
                   manager.index("void UIManager::nomad_reload()")]
    # A valid address must also preserve the current page until live transport
    # serialization succeeds; lock contention is retried by the owner loop.
    assert live.index("RouterLock router_lock;") < \
        live.index("_nomadnet_screen->begin_navigation(_nomad_url.str())")


def test_launcher_transition_has_one_final_focus_owner():
    """Leaving and restoring Home must not transiently focus later tiles."""
    home = (INCLUDE / "HomeScreen.cpp").read_text()
    show_start = home.index("void HomeScreen::show()")
    hide_start = home.index("void HomeScreen::hide()", show_start)
    show = home[show_start:hide_start]
    hide_end = home.index("void HomeScreen::clicked", hide_start)
    hide = home[hide_start:hide_end]

    # Adding the first tile to an empty LVGL group auto-focuses it. Freeze the
    # complete ordered rebuild and make Messages the sole explicit owner.
    assert "lv_group_focus_freeze(group, true);" in show
    assert "lv_group_focus_freeze(group, false);" in show
    assert show.index("lv_group_focus_freeze(group, true);") < show.index("lv_group_add_obj")
    assert show.index("lv_group_focus_freeze(group, false);") < show.index("lv_group_focus_obj(_buttons[0])")

    # Hide must detach every non-owner before the current owner; removing an
    # owner early makes LVGL focus each surviving launcher tile synchronously.
    assert "lv_obj_t* focused = lv_group_get_focused(group);" in hide
    non_owner_remove = re.search(
        r"if \(button == focused\)\s*\{.*?\}\s*else\s*\{\s*lv_group_remove_obj\(button\);",
        hide,
        re.S,
    )
    assert non_owner_remove
    assert "if (focused_is_launcher) lv_group_remove_obj(focused);" in hide
    assert non_owner_remove.start() < hide.index(
        "if (focused_is_launcher) lv_group_remove_obj(focused);"
    )


def test_nomadnet_directory_uses_one_coherent_focus_style():
    """The focused row must not gain the default blue keypad outline later."""
    screen = (INCLUDE / "NomadNetScreen.cpp").read_text()
    add_row_start = screen.index("auto add_row=")
    add_row_end = screen.index("if(view==View::START)", add_row_start)
    add_row = screen[add_row_start:add_row_end]

    assert "Theme::primaryPressed(),LV_STATE_FOCUSED" in add_row
    assert "lv_obj_set_style_outline_width(button,0,LV_STATE_FOCUS_KEY);" in add_row
    assert add_row.index("Theme::primaryPressed(),LV_STATE_FOCUSED") < add_row.index(
        "lv_obj_set_style_outline_width(button,0,LV_STATE_FOCUS_KEY);"
    )


def test_nomadnet_cache_blocker_boundaries_are_closed():
    manager = (INCLUDE / "UIManager.cpp").read_text()
    header = (INCLUDE / "UIManager.h").read_text()
    cache = (INCLUDE / "NomadNetCache.cpp").read_text()
    storage = (ROOT / "lib/tdeck_ui/Hardware/TDeck/NomadNetStorageSD.cpp").read_text()

    # Every navigation owns transport/mailbox/cache actions by a monotonically
    # advancing generation, and old transport is reconciled before a hit publishes.
    assert "_nomad_navigation_generation" in header
    open_page = manager[manager.index("void UIManager::nomad_open("):
                        manager.index("void UIManager::nomad_reload()")]
    assert "nomad_supersede_transport" in open_page
    cache_hit = manager[manager.index("if (_nomad_state == NomadState::CACHE)"):
                        manager.index("RouterLock router_lock", manager.index("if (_nomad_state == NomadState::CACHE)"))]
    assert "_nomad_navigation_generation" in cache_hit
    response = manager[manager.index("case NomadNet::AsyncMailbox::Kind::RESPONSE:"):
                       manager.index("case NomadNet::AsyncMailbox::Kind::NONE:")]
    assert "event.generation" in manager
    assert "_nomad_cache_pending_generation" in response

    # Commit readback is one fixed bounded streaming scratch buffer, never a
    # second full internal-heap vector while the PSRAM body remains owned.
    verify = cache[cache.index("case Operation::VERIFY_BODY"):
                   cache.index("case Operation::VERIFY_META")]
    assert "readStep(stageBody(), io_" not in verify
    assert "verify_scratch_" in verify
    assert "verify_hash_" in verify

    # Production directory enumeration must preserve errno fidelity instead of
    # collapsing exists/openNextFile failures to missing/EOF.
    listing = storage[storage.index("StorageResult NomadNetStorageSD::beginList"):]
    assert "::opendir" in listing and "::readdir" in listing
    assert "errno" in listing and "::closedir" in listing
    assert "SD.exists(p)" not in listing
    assert "openNextFile" not in listing

    removal = storage[storage.index("StorageResult NomadNetStorageSD::remove"):
                      storage.index("StorageResult NomadNetStorageSD::rename")]
    assert "mountedPath(p" in removal
    assert "::unlink(" in removal
    assert "errno==ENOENT?StorageResult::MISS:ioResult()" in removal
    assert "SD.exists" not in removal and "SD.remove" not in removal

    # Live admission is non-destructive until Router serialization succeeds.
    # Contention leaves an explicit owner-loop state that retries deterministically.
    live = manager[manager.index("void UIManager::nomad_begin_live_transport()"):
                   manager.index("void UIManager::nomad_reload()")]
    assert live.index("RouterLock router_lock;") < live.index("begin_navigation")
    assert "if (!router_lock.acquired())" in live
    assert "_nomad_state = NomadState::LIVE_PENDING;" in live
    update = manager[manager.index("void UIManager::nomad_update()"):
                     manager.index("void UIManager::on_nomad_link_established")]
    assert "if (_nomad_state == NomadState::LIVE_PENDING)" in update
    assert "nomad_begin_live_transport();" in update


def test_network_transition_has_one_final_focus_owner():
    """Network hide/show must not transiently leave the last row focused."""
    screen = (INCLUDE / "NetworkScreen.cpp").read_text()
    show_start = screen.index("void NetworkScreen::show()")
    hide_start = screen.index("void NetworkScreen::hide()", show_start)
    clicked_start = screen.index("void NetworkScreen::clicked", hide_start)
    show = screen[show_start:hide_start]
    hide = screen[hide_start:clicked_start]

    assert "lv_group_focus_freeze(g, true);" in show
    assert "lv_group_focus_freeze(g, false);" in show
    assert show.index("lv_group_focus_freeze(g, true);") < show.index("lv_group_add_obj")
    assert show.index("lv_group_focus_freeze(g, false);") < show.index(
        "lv_group_focus_obj(_buttons[0]);"
    )
    assert show.count("lv_group_focus_obj") == 1

    assert "lv_obj_t* focused = lv_group_get_focused(g);" in hide
    assert "if (focused_is_network) lv_group_remove_obj(focused);" in hide
    assert hide.index("if (object == focused)") < hide.index(
        "if (focused_is_network) lv_group_remove_obj(focused);"
    )


def test_bounded_nomadnet_fonts_match_display_allowlist():
    expected = set(range(0x20, 0x7F)) | set(range(0xA0, 0x180))
    expected |= set(range(0x2190, 0x219A))
    expected |= {
        0x2007, 0x2008, 0x2009, 0x200A, 0x200B,
        0x2010, 0x2012, 0x2013, 0x2014, 0x2015,
        0x2018, 0x2019, 0x201A, 0x201C, 0x201D, 0x201E,
        0x2020, 0x2021, 0x2022, 0x2026, 0x2030, 0x2032,
        0x2033, 0x2039, 0x203A, 0x2044, 0x2052,
        0x20A1, 0x20A3, 0x20A4, 0x20A6, 0x20A7, 0x20A9,
        0x20AB, 0x20AC, 0x20AD, 0x20AE, 0x20B1, 0x20B2,
        0x20B4, 0x20B5, 0x20B8, 0x20B9, 0x20BA, 0x20BC, 0x20BD,
        0x2500, 0x2550, 0x2551, 0x2554, 0x2557,
        0x255A, 0x255D, 0x2588, 0x2594, 0x25A0,
    }
    for size in (12, 16):
        source = (ROOT / "lib" / "tdeck_ui" / "UI" / "Fonts" /
                  f"nomadnet_font_{size}.c").read_text()
        encoded = {int(value, 16) for value in re.findall(r"/\* U\+([0-9A-F]+)", source)}
        assert encoded == expected
        assert f".get_glyph_dsc = nomadnet_font_{size}_get_glyph_dsc" in source
        assert f".get_glyph_bitmap = nomadnet_font_{size}_get_glyph_bitmap" in source
        assert "nomadnet_font_has_codepoint(letter)" in source


def test_generated_font_compression_is_enabled_in_lvgl():
    config = (ROOT / "lib" / "lv_conf.h").read_text()
    for size in (12, 16):
        source = (ROOT / "lib" / "tdeck_ui" / "UI" / "Fonts" /
                  f"nomadnet_font_{size}.c").read_text()
        assert ".bitmap_format = 1" in source
        assert "#if !LV_USE_FONT_COMPRESSED" in source
        assert "#error \"NomadNet fonts require LV_USE_FONT_COMPRESSED=1\"" in source
    assert "#define LV_USE_FONT_COMPRESSED 1" in config


def test_directory_icons_use_lvgl_symbol_font_separately_from_remote_text():
    screen = (INCLUDE / "NomadNetScreen.cpp").read_text()
    assert "add_row(LV_SYMBOL" not in screen
    assert "const char* symbol=nullptr" in screen
    assert "lv_label_set_text(icon,symbol)" in screen
    assert "lv_obj_set_style_text_font(icon,&lv_font_montserrat_12,0)" in screen
    for symbol in ("LV_SYMBOL_DIRECTORY", "LV_SYMBOL_SAVE", "LV_SYMBOL_LIST", "LV_SYMBOL_EDIT"):
        assert f",{symbol});" in screen


def test_nomadnet_latency_and_path_lifecycle_contracts():
    manager_cpp = (INCLUDE / "UIManager.cpp").read_text()
    main_cpp = (ROOT / "src" / "main.cpp").read_text()
    screen_h = (INCLUDE / "NomadNetScreen.h").read_text()

    # User actions must be serviced before the known 5-15 second persistence
    # boundary, otherwise Back/Open remains frozen behind flash erase/GC.
    assert main_cpp.index("ui_manager->update();") < main_cpp.index("reticulum->should_persist_data();")

    # Terminal browser cancellation must be serviced before another inbound
    # transport pass. Resource receive/assembly is synchronous on this owner
    # loop and must not repeatedly outrun an already-published Back/Home.
    assert main_cpp.index("ui_manager->service_nomad_terminal_action();") < \
        main_cpp.index("reticulum->loop();")

    # Back/Home published immediately after Save must not remain queued behind
    # the synchronous NomadNet library transaction. Drain only the bounded
    # Save->terminal batch; ordinary Open actions remain one-per-pass.
    action_update = manager_cpp[manager_cpp.index("void UIManager::nomad_update_user_actions()"):
                                manager_cpp.index("void UIManager::nomad_release_request()")]
    assert "ActionMailbox::CAPACITY + 1" in action_update
    assert "action.kind != NomadNet::UserActionKind::SAVE" in action_update
    assert "_nomad_actions.terminal_pending()" in action_update
    assert manager_cpp.index("nomad_update_user_actions();") < manager_cpp.index("nomad_update_library();")

    # Requesting is ambiguous. Once the dependency reports Resource progress,
    # expose that distinct phase instead of leaving the stale request status.
    assert "case NomadNet::AsyncMailbox::Kind::PROGRESS:" in manager_cpp
    assert 'set_status("Receiving page...")' in manager_cpp
    request_start = manager_cpp[manager_cpp.index("void UIManager::nomad_send_request()"):
                                manager_cpp.index("void UIManager::nomad_update()")]
    assert "set_resource_started_callback" in request_start
    assert "set_progress_callback" in manager_cpp
    assert "on_nomad_resource_progress" in manager_cpp

    refresh = manager_cpp[manager_cpp.index("void UIManager::nomad_refresh_nodes()"):
                          manager_cpp.index("void UIManager::nomad_update_library()")]
    assert refresh.index("Transport::has_path(destination_hash)") < refresh.index("Identity::recall(destination_hash)")

    # Browser rendering must not trigger the expensive path-table/library poll.
    assert "directory_visible() const" in screen_h
    assert "std::atomic<bool> _directory_visible" in screen_h
    update_library = manager_cpp[manager_cpp.index("void UIManager::nomad_update_library()"):
                                 manager_cpp.index("void UIManager::nomad_update_user_actions()")]
    assert "directory_visible()" in update_library

    back = manager_cpp[manager_cpp.index("void UIManager::back()"):
                       manager_cpp.index("void UIManager::home()")]
    assert back.index("handle_library_back()") < back.index("nomad_stop_transport();")


def test_nomadnet_requests_are_anonymous_and_back_cleanup_is_serialized():
    manager_cpp = (INCLUDE / "UIManager.cpp").read_text()

    # Canonical NomadNet identifies only for nodes with an explicit per-node
    # identify-on-connect policy. The established-link event delegates that
    # policy decision before request creation instead of identifying every link.
    link_event = manager_cpp[manager_cpp.index("case NomadNet::AsyncMailbox::Kind::LINK_ESTABLISHED:"):
                             manager_cpp.index("case NomadNet::AsyncMailbox::Kind::LINK_CLOSED:")]
    assert ".identify(" not in link_event
    assert "nomad_send_request();" in link_event

    # Link teardown cancels an in-flight Resource and updates its shared request
    # receipt. Observe that cancellation before using the compatibility pending-
    # receipt cleanup, and keep both mutations under the Reticulum owner lock.
    stop = manager_cpp[manager_cpp.index("bool UIManager::nomad_stop_transport()"):
                       manager_cpp.index("bool UIManager::nomad_refresh_path_after_link_failure()")]
    assert "RouterLock router_lock;" in stop
    assert stop.index("_nomad_link.teardown()") < stop.index("nomad_release_request();")

    reopen = manager_cpp[manager_cpp.index("void UIManager::nomad_open("):
                         manager_cpp.index("void UIManager::nomad_reload()")]
    assert "RouterLock router_lock;" in reopen
    assert reopen.index("_nomad_link.teardown()") < reopen.index("nomad_release_request();")

    update = manager_cpp[manager_cpp.index("void UIManager::nomad_update()"):
                         manager_cpp.index("void UIManager::on_nomad_link_established")]
    assert "RouterLock router_lock;" in update
    assert "nomad_stop_transport();" in update


def test_nomadnet_uses_real_jetbrains_mono_nl_faces_at_each_size():
    glyphs_h = (INCLUDE / "NomadNetGlyphs.h").read_text()
    browser_cpp = (INCLUDE / "NomadNetScreen.cpp").read_text()
    fonts = INCLUDE.parent / "Fonts"
    faces = {
        "regular": "",
        "bold": "_bold",
        "italic": "_italic",
        "bold_italic": "_bold_italic",
    }

    for size in (12, 16):
        for style, suffix in faces.items():
            symbol = f"nomadnet_font_{size}{suffix}"
            generated = (fonts / f"{symbol}.c").read_text()
            assert f"LV_FONT_DECLARE({symbol})" in glyphs_h
            assert generated.count("/* U+") == 385
            assert '/* U+00AD "­" */' in generated
            assert '/* U+20BC "₼" */' in generated
            assert "NomadNetFontCoverage.h" in generated
            assert "nomadnet_font_has_codepoint" in generated
            assert "JetBrains Mono NL" in generated
            assert f"{style.replace('_', ' ').title()}" in generated
            assert "Version 2.304" in generated
            assert "LICENSE-JetBrains-Mono-OFL-1.1.txt" in generated

    license_text = (fonts / "LICENSE-JetBrains-Mono-OFL-1.1.txt").read_text()
    assert "Copyright 2020 The JetBrains Mono Project Authors" in license_text
    assert "SIL OPEN FONT LICENSE Version 1.1" in license_text
    noto_license = (fonts / "LICENSE-Noto-Sans-OFL-1.1.txt").read_text()
    assert "Copyright 2022 The Noto Project Authors" in noto_license
    assert "SIL OPEN FONT LICENSE Version 1.1" in noto_license

    assert "const lv_font_t* page_run_font" in browser_cpp
    assert "NomadNet::CompactPage::BOLD" in browser_cpp
    assert "NomadNet::CompactPage::ITALIC" in browser_cpp
    assert "&nomadnet_font_12_bold" in browser_cpp
    assert "&nomadnet_font_12_italic" in browser_cpp
    assert "&nomadnet_font_12_bold_italic" in browser_cpp
    assert "&nomadnet_font_16_bold" in browser_cpp
    assert "&nomadnet_font_16_italic" in browser_cpp
    assert "&nomadnet_font_16_bold_italic" in browser_cpp
    assert "dsc.font=page_run_font(run, fragment.large_font);" in browser_cpp
    assert "dsc.letter_space=0;" in browser_cpp
    assert "?1:0,LV_TEXT_FLAG_NONE" not in browser_cpp


def test_nomadnet_heading_layout_uses_retained_depth_without_overwriting_colors():
    browser_cpp = (INCLUDE / "NomadNetScreen.cpp").read_text()
    layout = browser_cpp[
        browser_cpp.index("bool NomadNetScreen::layout_page()") :
        browser_cpp.index("void NomadNetScreen::draw_page(")
    ]

    assert "heading_uses_large_font(block.depth)" in layout
    assert "heading_indent_spaces(block.depth)" in layout
    assert "heading_bottom_spacing(block.depth)" in layout
    assert "heading_display_level(block.depth)" in layout
    assert "whitespace&&x==indent&&!heading" in layout
    assert "run.foreground=" not in layout
    assert "run.background=" not in layout

    draw = browser_cpp[
        browser_cpp.index("void NomadNetScreen::draw_page(") :
        browser_cpp.index("void NomadNetScreen::select_link(")
    ]
    assert "fragment.heading_starts_band()" in draw
    assert "content_area.x2" in draw
    assert "heading_background(fragment.heading_level())" in draw
    assert "resolve_effective_foreground(" in draw
    assert draw.index("fragment.heading_starts_band()") < draw.index(
        "run.style&NomadNet::CompactPage::HAS_BACKGROUND"
    )


def test_nomadnet_page_fonts_do_not_leak_into_navigation_widgets():
    browser_cpp = (INCLUDE / "NomadNetScreen.cpp").read_text()
    constructor = browser_cpp[
        browser_cpp.index("NomadNetScreen::NomadNetScreen()") :
        browser_cpp.index("NomadNetScreen::~NomadNetScreen()")
    ]
    directory = browser_cpp[
        browser_cpp.index("void NomadNetScreen::render_directory(View view)") :
        browser_cpp.index("void NomadNetScreen::detach_focusables(")
    ]
    layout = browser_cpp[
        browser_cpp.index("bool NomadNetScreen::layout_page()") :
        browser_cpp.index("void NomadNetScreen::draw_page(")
    ]
    draw = browser_cpp[
        browser_cpp.index("void NomadNetScreen::draw_page(") :
        browser_cpp.index("void NomadNetScreen::select_link(")
    ]

    assert "nomadnet_font_" not in constructor
    assert "nomadnet_font_" not in directory
    assert "page_run_font(run,large)" in layout
    assert "dsc.font=page_run_font(run, fragment.large_font);" in draw


def test_nomadnet_navigation_keeps_theme_font_with_remote_glyph_fallback():
    browser_cpp = (INCLUDE / "NomadNetScreen.cpp").read_text()
    selector = browser_cpp[
        browser_cpp.index("const lv_font_t* navigation_font_12()") :
        browser_cpp.index("const lv_font_t* page_run_font(")
    ]
    constructor = browser_cpp[
        browser_cpp.index("NomadNetScreen::NomadNetScreen()") :
        browser_cpp.index("NomadNetScreen::~NomadNetScreen()")
    ]
    directory = browser_cpp[
        browser_cpp.index("void NomadNetScreen::render_directory(View view)") :
        browser_cpp.index("void NomadNetScreen::detach_focusables(")
    ]

    assert "font=lv_font_montserrat_12" in selector
    assert "font.fallback=&nomadnet_font_12" in selector
    assert constructor.count("navigation_font_12()") == 2
    assert directory.count("navigation_font_12()") == 3


def test_nomadnet_draw_preserves_authored_colors_for_links_and_focus():
    browser_cpp = (INCLUDE / "NomadNetScreen.cpp").read_text()
    draw = browser_cpp[
        browser_cpp.index("void NomadNetScreen::draw_page(") :
        browser_cpp.index("void NomadNetScreen::select_link(")
    ]

    assert "dsc.color=lv_color_hex(NomadNet::resolve_effective_foreground(" in draw
    assert "_page,run,fragment.heading_level(),Theme::TEXT_PRIMARY" in draw
    assert "run.link_index>=0?Theme::primaryLight()" not in draw
    assert "selected?Theme::primaryPressed()" not in draw
    assert "bg.bg_color=lv_color_hex(run.background)" in draw
    assert "focus.bg_opa=LV_OPA_TRANSP" in draw
    assert "focus.border_color=lv_color_hex(NomadNet::resolve_focus_border(" in draw


def test_nomadnet_bold_body_text_keeps_body_font_metrics():
    browser_cpp = (INCLUDE / "NomadNetScreen.cpp").read_text()
    fonts = INCLUDE.parent / "Fonts"
    layout_start = browser_cpp.index("const bool heading=")
    layout = browser_cpp[layout_start : browser_cpp.index(
        "const lv_font_t* font=page_run_font", layout_start
    )]

    assert "block.type==NomadNet::BlockType::HEADING" in layout
    assert "large_heading=heading&&NomadNet::heading_uses_large_font(block.depth)" in layout
    assert "NomadNet::CompactPage::BOLD" not in layout

    for size in (12, 16):
        metrics = set()
        bitmaps = {}
        for suffix in ("", "_bold", "_italic", "_bold_italic"):
            source = (fonts / f"nomadnet_font_{size}{suffix}.c").read_text()
            line_height_match = re.search(r"\.line_height = (\d+)", source)
            base_line_match = re.search(r"\.base_line = (\d+)", source)
            assert line_height_match is not None
            assert base_line_match is not None
            line_height = line_height_match.group(1)
            base_line = base_line_match.group(1)
            metrics.add((line_height, base_line))
            bitmap = source[source.index("glyph_bitmap[]") : source.index("GLYPH DESCRIPTION")]
            bitmaps[suffix] = bytes(int(value, 16) for value in re.findall(r"0x([0-9a-fA-F]{2})", bitmap))
        assert len(metrics) == 1
        assert bitmaps[""] != bitmaps["_bold"]
        assert bitmaps["_italic"] != bitmaps["_bold_italic"]


def test_nomadnet_font_generator_pins_sources_and_tools():
    generator = (ROOT / "tools" / "fonts" / "generate_nomadnet_fonts.py").read_text()

    assert "JetBrainsMono/releases/download/v2.304" in generator
    assert "2984c575fdce412ee02b2baaba67672b9a9434d8" in generator
    assert generator.count("require_digest(") >= 3
    assert 'fontTools.__version__ != "4.63.0"' in generator
    assert 'version != "1.5.3"' in generator
    assert "require_noto_instance" in generator


def test_nomadnet_same_destination_navigation_reuses_active_link():
    screen_h = (INCLUDE / "NomadNetScreen.h").read_text()
    manager_cpp = (INCLUDE / "UIManager.cpp").read_text()

    assert "bool set_page(const NomadNet::Document& document);" in screen_h

    reopen = manager_cpp[manager_cpp.index("void UIManager::nomad_open("):
                         manager_cpp.index("void UIManager::nomad_reload()")]
    assert "same_destination" in reopen
    assert "_nomad_link.status() == Type::Link::ACTIVE" in reopen
    assert reopen.index("if (same_destination") < reopen.index("_nomad_link.teardown()")
    same_site = reopen[reopen.index("if (same_destination"):reopen.index("_nomad_link.teardown()")]
    assert "nomad_send_request();" in same_site
    assert "Transport::request_path" not in same_site

    response = manager_cpp[manager_cpp.index("case NomadNet::AsyncMailbox::Kind::RESPONSE:"):
                           manager_cpp.index("case NomadNet::AsyncMailbox::Kind::NONE:")]
    assert response.index("normalize_response") < response.index("nomad_finish_request_keep_link();")
    assert response.index("document.malformed && document.blocks.empty()") < response.index(
        "nomad_finish_request_keep_link();"
    )
    malformed = response[response.index("if (!NomadNet::normalize_response"):response.index(
        "nomad_finish_request_keep_link();"
    )]
    assert "nomad_stop_transport();" in malformed
    assert "nomad_apply_page_document(document, false)" in response
    assert "if (!page_applied)" in response
    assert response.index("nomad_apply_page_document(document, false)") < response.index(
        "nomad_finish_request_keep_link();"
    )
    application_failure = response[response.index("if (!page_applied)"):
                                   response.index("const bool has_password")]
    assert "nomad_stop_transport();" in application_failure
    retained = response[response.index("_nomad_link.status() == Type::Link::ACTIVE"):]
    assert "_nomad_destination_hash.toHex() == _nomad_url.destination_hex" in retained
    assert "nomad_stop_transport();" in retained


def test_nomadnet_physical_test_hooks_are_isolated_and_owner_queued():
    main = (ROOT / "src/main.cpp").read_text()
    header = (INCLUDE / "UIManager.h").read_text()
    implementation = (INCLUDE / "UIManager.cpp").read_text()
    runner = (ROOT / "tests/hardware/nomadnet_tdeck_harness.py").read_text()
    server = (ROOT / "tests/native/nomadnet_x86_flow/lan_server.py").read_text()

    assert "T:NOMAD <url>" in main
    assert "T:NOMAD_STATUS" in main
    assert "ui_manager->test_nomad_open" in main
    assert "ui_manager->test_nomad_status" in main

    declaration = header[header.index(
        "#if defined(PYXIS_TEST_HOOKS) || defined(PYXIS_NOMAD_LINK_DIAGNOSTIC)") :]
    assert "bool test_nomad_open(const std::string& address);" in declaration
    assert "void test_nomad_status() const;" in declaration

    open_start = implementation.index("bool UIManager::test_nomad_open")
    open_end = implementation.index("void UIManager::test_nomad_status", open_start)
    open_body = implementation[open_start:open_end]
    assert "_nomad_actions.publish(NomadNet::UserActionKind::OPEN" in open_body
    assert "nomad_open(" not in open_body[open_body.index("{") + 1 :]

    status_start = implementation.index("void UIManager::test_nomad_status")
    status_body = implementation[status_start : status_start + 2500]
    for field in ("state=", "path=", "identity=", "link=", "request=",
                  "response=", "free=", "largest=", "minimum="):
        assert field in status_body

    assert "PYXIS_TEST_HOOKS" in header
    assert "PYXIS_TEST_HOOKS" in implementation
    assert "T:NOMAD_STATUS" in runner
    assert "LAN SERVER link established" in server
    assert "LAN SERVER request path={path}" in server
    assert "Guru Meditation" in runner
    assert "watchdog" in runner.lower()


def test_nomadnet_active_window_defers_only_nonessential_owner_loop_work():
    main = (ROOT / "src/main.cpp").read_text()
    header = (INCLUDE / "UIManager.h").read_text()
    implementation = (INCLUDE / "UIManager.cpp").read_text()

    assert "bool nomad_link_pending() const;" in header
    assert "bool UIManager::nomad_link_pending() const" in implementation
    assert "const bool nomad_link_pending = ui_manager && ui_manager->nomad_link_pending();" in main
    assert "const bool nomad_busy = nomad_suspend_nonessential && nomad_link_pending;" in main
    assert "const bool nomad_busy = false;" in main
    assert 'line == "T:NOMAD_MODE NORMAL"' in main
    assert 'line == "T:NOMAD_MODE SUSPEND"' in main

    # Python RNS continues socket ingress and Link/proof processing throughout
    # establishment. The embedded owner-task equivalent must remain unconditional.
    reticulum = main[main.index("// Process Reticulum") : main.index("// Best-effort instantaneous RSSI")]
    assert "if (!nomad_busy)" not in reticulum
    assert "reticulum->loop();" in reticulum
    assert main.index("service_nomad_terminal_action();") < main.index("reticulum->loop();")

    persistence = main[main.index("// Periodically persist identity/transport data") :
                       main.index("// Reticulum::loop() above")]
    assert "if (!nomad_busy)" in persistence
    assert "reticulum->should_persist_data();" in persistence

    periodic = main[main.index("// Periodic announce") : main.index("// Check for TCP reconnection")]
    assert periodic.count("!nomad_busy") >= 2
    assert "announce_reachable_destinations();" in periodic
    assert "request_messages_from_propagation_node();" in periodic

    # Diagnostic activity suspension is bounded to the pending Link epoch. It
    # ends on ACTIVE, CLOSED, timeout, Back/Home, or replacement navigation.
    predicate = implementation[implementation.index("bool UIManager::nomad_link_pending() const") :]
    predicate = predicate[:predicate.index("}") + 1]
    assert "_nomad_state == NomadState::LINK" in predicate
    assert "RNS::Type::Link::ACTIVE" in predicate
    assert "RNS::Type::Link::CLOSED" in predicate
    stop = implementation[implementation.index("bool UIManager::nomad_stop_transport()") :
                          implementation.index("bool UIManager::nomad_refresh_path_after_link_failure()")]
    assert "_nomad_state = NomadState::IDLE;" in stop


def test_nomadnet_persisted_heard_announces_are_not_pruned_by_route_state():
    manager_cpp = (INCLUDE / "UIManager.cpp").read_text()
    manager_h = (INCLUDE / "UIManager.h").read_text()
    refresh = manager_cpp[manager_cpp.index("void UIManager::nomad_refresh_nodes()"):
                          manager_cpp.index("void UIManager::nomad_update_library()")]

    # Canonical NomadNet persists its bounded announce stream independently of
    # current route availability. A reboot or expired path must not erase the
    # user's heard-node history from Pyxis's durable library.
    assert "remove_heard_node" not in refresh
    assert 'AnnounceHandler("nomadnetwork.node")' in manager_cpp
    assert "Transport::register_announce_handler(_nomad_announce_handler)" in manager_cpp
    hear = manager_cpp[manager_cpp.index("void UIManager::nomad_hear_node"):
                       manager_cpp.index("void UIManager::nomad_refresh_nodes")]
    assert "_nomad_library.hear_node" in hear
    assert "_nomad_library_dirty = true;" in hear

    # The announce callback captures this, so its Transport registration must
    # have the same lifetime as that exact UIManager. A process-global handler
    # can outlive its manager or be deregistered by a different manager.
    assert "RNS::HAnnounceHandler _nomad_announce_handler;" in manager_h
    assert "static std::shared_ptr<NomadNetAnnounceHandler> s_nomad_announce_handler" not in manager_cpp
    assert "s_nomad_announce_handler" not in manager_cpp
    assert "Transport::register_announce_handler(_nomad_announce_handler)" in manager_cpp

    destructor = manager_cpp[manager_cpp.index("UIManager::~UIManager()"):
                             manager_cpp.index("bool UIManager::init()")]
    assert "RouterLock router_lock;" in destructor
    assert "Transport::deregister_announce_handler(_nomad_announce_handler)" in destructor
    assert destructor.index("RouterLock router_lock;") < destructor.index(
        "Transport::deregister_announce_handler(_nomad_announce_handler)")
